slug = "iphuck-10"
title = "iPhuck 10"
author = "Виктор Пелевин"
language = "ru"
text_source = "https://reader.fantasy-worlds.org/book/26447/read.html"
audio_source = "https://www.youtube.com/watch?v=C2gdPdvCDP0"
narrator = "Александр Клюквин"
